version: "2"

linters:
  enable-all: true
  disable:
    - wsl_v5
    - exhaustruct
    - varnamelen
    - cyclop
    - funlen
    - gocognit
    - gocyclo
    - lll
    - maintidx
    - nestif
    - mnd  # magic number detector, peut être trop strict

exclusions:
  presets:
    - comments
    - std-error-handling
    - common-false-positives
    - legacy
  warn-unused: true

formatters:
  enable:
    - gofmt
    - goimports
    - gofumpt
  settings:
    gofmt:
      simplify: true
      rewrite-rules:
        - pattern: "interface{}"
          replacement: "any"
        - pattern: "a[b:len(a)]"
          replacement: "a[b:]"

run:
  timeout: 5m
  concurrency: 4
  modules-download-mode: readonly
  go: '1.24.5'

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    line-number:
      path: stdout
  sort-results: true
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/gmllt/enum)
  
  gocritic:
    enabled-checks:
      - nestingReduce
      - unnamedResult
      - ruleguard
      - truncateCmp
    
  revive:
    rules:
      - name: exported
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"